name: Run SI Live Daily

on:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 12:30 PM IST (07:00 UTC)
  workflow_dispatch:

jobs:
  run-si-live:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy yfinance joblib statsmodels xgboost openpyxl gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create service account key file
      run: |
        echo "${{ secrets.GDRIVE_SERVICE_KEY }}" | base64 -d > service_account.json

    - name: Run SI Live script
      run: |
        python si_live.py

    - name: Upload result to Google Drive
      env:
        GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      run: |
        python - <<'EOF'
        import gspread
        from google.oauth2.service_account import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        creds = Credentials.from_service_account_file("service_account.json", scopes=["https://www.googleapis.com/auth/drive"])
        service = build("drive", "v3", credentials=creds)

        # File to upload
        file_path = "live_portfolio_results.json"
        file_name = "live_portfolio_results.json"

        # Search for existing file
        results = service.files().list(q=f"name='{file_name}' and trashed=false", fields="files(id)").execute()
        files = results.get("files", [])

        if files:
            file_id = files[0]["id"]
            media = MediaFileUpload(file_path, mimetype="application/json")
            updated = service.files().update(fileId=file_id, media_body=media).execute()
            print("✅ File updated successfully:", updated.get("id"))
        else:
            file_metadata = {"name": file_name}
            media = MediaFileUpload(file_path, mimetype="application/json")
            uploaded = service.files().create(body=file_metadata, media_body=media, fields="id").execute()
            print("✅ File uploaded successfully:", uploaded.get("id"))
        EOF
